# Generated by Django 5.2.15 on 2026-07-31 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='item',
            new_name='items_item_owner_i_b97481_idx',
            old_name='items_item_owner_i_7fb4d6_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='items_item_owner_i_a6dbfb_idx',
            old_name='items_item_owner_i_09c54d_idx',
        ),
    ]
