# Generated by Django 5.2.15 on 2026-07-31 04:11

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_sync_item_index_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=items.models.item_photo_path),
        ),
    ]
