# Generated by Django 5.2.15 on 2026-07-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_opaque_upload_paths'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationnode',
            name='unique_location_code_per_parent',
        ),
        migrations.RemoveConstraint(
            model_name='locationnode',
            name='unique_root_location_code',
        ),
        migrations.AddConstraint(
            model_name='locationnode',
            constraint=models.UniqueConstraint(condition=models.Q(('floor_plan__isnull', False), ('parent__isnull', False)), fields=('home', 'floor_plan', 'parent', 'code'), name='unique_location_code_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='locationnode',
            constraint=models.UniqueConstraint(condition=models.Q(('floor_plan__isnull', True), ('parent__isnull', False)), fields=('home', 'parent', 'code'), name='unique_location_code_per_parent_no_plan'),
        ),
        migrations.AddConstraint(
            model_name='locationnode',
            constraint=models.UniqueConstraint(condition=models.Q(('floor_plan__isnull', False), ('parent__isnull', True)), fields=('home', 'floor_plan', 'code'), name='unique_root_location_code'),
        ),
        migrations.AddConstraint(
            model_name='locationnode',
            constraint=models.UniqueConstraint(condition=models.Q(('floor_plan__isnull', True), ('parent__isnull', True)), fields=('home', 'code'), name='unique_root_location_code_no_plan'),
        ),
    ]
