# Generated by Django 5.2.15 on 2026-07-31 04:11

import homes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=homes.models.floor_plan_background_path),
        ),
    ]
